### ISSUE TITLE
Is there any plans to add support for universal rendering?

### ISSUE THREAD

**Issue by robertdumitrescu** [emn178/angular2-chartjs#15]
Is there any plans to add support for universal rendering?

It would be nice if the whole application wouldn't fail to bootstrap when universal rendering is used. 

I also added a ticket on angular/issues.
https://github.com/angular/angular/issues/15261

**Comment by emn178** [comment]
hi, I try to change this [line](https://github.com/emn178/angular2-chartjs/blob/master/src/chart.module.ts#L1) to
```JavaScript
if (typeof window === 'object') {
  require('chart.js');
}
```
It can pass build and work in browser but raise runtime error in server side.
```
EXCEPTION: Chart is not defined
ORIGINAL STACKTRACE:
ReferenceError: Chart is not defined
    at ChartComponent.ngOnInit (/home/lilee/github/universal-starter/dist/server/index.js:40703:26)
    at Wrapper_ChartComponent.detectChangesInInputProps (/ChartModule/ChartComponent/wrapper.ngfactory.js:48:53)
    at AppView._View_AppComponent0.detectChangesInternal (/AppModule/AppComponent/component.ngfactory.js:199:29)
    at AppView.detectChanges (/home/lilee/github/universal-starter/dist/server/index.js:50747:14)
    at AppView.detectViewChildrenChanges (/home/lilee/github/universal-starter/dist/server/index.js:50773:19)
    at AppView._View_AppComponent_Host0.detectChangesInternal (/AppModule/AppComponent/host.ngfactory.js:31:8)
    at AppView.detectChanges (/home/lilee/github/universal-starter/dist/server/index.js:50747:14)
    at ViewRef_.detectChanges (/home/lilee/github/universal-starter/dist/server/index.js:36807:20)
    at /home/lilee/github/universal-starter/dist/server/index.js:22634:84
    at Array.forEach (native)
Error in SSR, serving for direct CSR
```
I don't know Angular Universal too much. Is this normal?
